"""Deterministically generated by NDS — the database connection every
generated app uses. Do not hand-edit; this file is identical for every
venture by design, so the exact same code works unmodified against
SQLite (the local default) or the shared Postgres instance once
DATABASE_URL is set at deploy time.
"""

import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base

DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///./app.db")

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {},
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# Imported here, after Base is defined, not at the top of this file: models.py
# does `from database import Base`, so importing it any earlier would be a
# circular import with nothing defined yet. Python resolves this fine because
# this module is already in sys.modules (if partially initialized) by the time
# models.py asks for Base, which already exists above this line — registering
# every model's table with Base.metadata before create_all runs below.
import models  # noqa: E402

Base.metadata.create_all(bind=engine)

# models.py may optionally define seed_if_empty(db) for one-time reference/
# seed data — the only sanctioned place for it (never an
# @app.on_event("startup") handler in main.py, which a bare TestClient()
# never triggers).
if hasattr(models, "seed_if_empty"):
    _seed_db = SessionLocal()
    try:
        models.seed_if_empty(_seed_db)
    finally:
        _seed_db.close()
