"""Deterministically generated by NDS — the database connection every
generated app uses. Do not hand-edit; this file is identical for every
venture by design, so the exact same code works unmodified against
SQLite (the local default) or the shared Postgres instance once
DATABASE_URL is set at deploy time.
"""

import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base

DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///./app.db")

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {},
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

_initialized = False


def get_db():
    # Deliberately lazy, not at module import time — see this file's own
    # docstring in mvp_build.py for exactly why: table creation here no
    # longer depends on whether main.py imports `models` or `database`
    # first, since by the time any request reaches get_db(), every module
    # the app needs has already finished importing, full stop.
    global _initialized
    if not _initialized:
        import models  # noqa: E402  safe here: already fully imported by this point, whichever module triggered it first

        Base.metadata.create_all(bind=engine)
        if hasattr(models, "seed_if_empty"):
            _seed_db = SessionLocal()
            try:
                models.seed_if_empty(_seed_db)
            finally:
                _seed_db.close()
        _initialized = True

    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
